import type { Category } from "./game";

const logos = import.meta.glob("@/assets/asset_maxlearn/logo/*.png", {
  eager: true,
});

const logoMap: Record<string, string> = {};

for (const path in logos) {
  // Extract nama file tanpa ekstensi → misalnya "org1"
  const fileName = path.split("/").pop()?.split(".")[0] || "";
  // logos[path] is a module, ambil default export (url)
  logoMap[fileName] = (logos[path] as { default: string }).default;
}

export const categories: Category[] = [
  {
    id: 1,
    name: "Lembaga Eksekutif UMN",
    organizations: [
      {
        id: 1,
        name: "Badan Eksekutif Mahasiswa (BEM)",
        desc: "BEM (Badan Eksekutif Mahasiswa) UMN adalah organisasi kemahasiswaan yang berperan sebagai lembaga eksekutif tertinggi di tingkat universitas. Secara struktural, BEM UMN berada di bawah naungan Wakil Rektor Bidang Kemahasiswaan, Employability & Kewirausahaan yang bekerja sama langsung dengan pihak Student Development.",
        clue: "Organisasi yang mengawasi seluruh organisator di UMN",
        password: "BEM",
      },
    ],
  },
  {
    id: 2,
    name: "Lembaga Legislatif & Yudikatif UMN",
    organizations: [
      {
        id: 48,
        name: "Dewan Keluarga Besar Mahasiswa (DKBM)",
        desc: "Dewan Keluarga Besar Mahasiswa Universitas Multimedia Nusantara (DKBM UMN) adalah organisasi kemahasiswaan di UMN yang bertindak sebagai badan legislatif dan yudikatif tertinggi. DKBM UMN memiliki kabinet yang terdiri dari tiap perwakilan fakultas dan didirikan sejak 6 Januari 2011 dengan 5 divisi didalamnya. Kabinet DKBM UMN akan menjabat selama satu periode kepengurusan yang mengemban tugas dan menampung aspirasi mahasiswa serta mencoba mencari solusinya.",
        clue: "Organisasi yang sering nerima aspirasi dari mahasiswa",
        password: "DKBM",
        fallbackLogo: logoMap["dkbm"],
      },
    ],
  },
  {
    id: 3,
    name: "Kegiatan Mahasiswa",
    organizations: [
      {
        id: 49,
        name: "Starlight",
        desc: "Starlight merupakan salah satu acara pencarian bakat di bawah naungan Badan Eksekutif Mahasiswa Universitas Multimedia Nusantara (BEM UMN) yang berdiri sejak 2016. Kegiatan ini menjadi wadah ekspresi mahasiswa yang bersifat eksternal pertama, dengan visi menemukan individu paling bersinar—bagaikan bintang yang mampu menyalurkan bakat terbaiknya ke dunia.",
        clue: "Bukan sekadar tempat tampil berani, tapi tempat bakat bersinar sejati. Panggung gemerlap bagai kristal terang, di sinilah perjalanan bintang dimulai dan dikenang.",
        password: "STARLIGHT",
        fallbackLogo: logoMap["starlight"],
      },
      {
        id: 50,
        name: "UMN Festival",
        desc: "UFEST (UMN Festival) adalah kepanitiaan di bawah naungan BEM yang telah hadir sejak 2015. Awalnya bernama Ultima Festival, kemudian berganti menjadi UMN Festival. UFEST merupakan perayaan ulang tahun UMN yang terdiri dari lima rangkaian acara, yaitu Unveiling sebagai pembuka, E-Ulympic (kompetisi esports), U-Care (aksi sosial), Ulympic (perlombaan olahraga), dan Unify sebagai malam puncak berupa konser. UFEST mengajak seluruh civitas UMN untuk bersama-sama memeriahkan hari jadi universitas.",
        clue: "#YANGADANAGANYA🐲",
        password: "UFEST",
        fallbackLogo: logoMap["ufest"],
      },
      {
        id: 51,
        name: "Mister & Miss UMN",
        desc: "Mister & Miss UMN merupakan ajang pencarian duta kampus Universitas Multimedia Nusantara (UMN) yang memiliki peranan untuk memberikan dampak positif bagi seluruh anggota akademis kampus, menciptakan lingkungan yang inspiratif serta membina karakter guna meningkatkan integritas dalam rangka mencapai keunggulan akademik kampus.",
        clue: "Pasangan yang kelak menjadi wajah terdepan UMN",
        password: "MISTERMISS",
        fallbackLogo: logoMap["mistermiss"],
      },
      {
        id: 52,
        name: "Orientasi Mahasiswa Baru (OMB)",
        desc: "Orientasi Mahasiswa Baru (OMB) merupakan rangkaian penyambutan mahasiswa baru Universitas Multimedia Nusantara. OMB UMN hadir sebagai wadah bagi mahasiswa baru untuk mengenal lingkungan kampus, mengambil langkah awal di dunia perkuliahan, serta membangun integritas diri.",
        clue: "Gerbang pertama yang menyambut langkah awal mahasiswa baru",
        password: "OMB",
        fallbackLogo: logoMap["omb"],
      },
      {
        id: 53,
        name: "UMN Earth Caring Operation (UMN ECO)",
        desc: "UMN ECO adalah singkatan dari Earth Caring Operation, yaitu sebuah kegiatan yang berada di bawah naungan BEM UMN. UMN ECO bertujuan untuk meningkatkan kesadaran melalui aksi nyata dalam melestarikan lingkungan di bumi. Dengan slogan “We Act for The Better Earth,” UMN ECO hadir sebagai gerakan mahasiswa yang tidak hanya peduli terhadap isu lingkungan, tetapi juga aktif menciptakan solusi melalui kegiatan edukatif, kolaboratif, dan berorientasi pada dampak nyata.",
        clue: "Haters pembuang sampah sembarangan",
        password: "ECO",
        fallbackLogo: logoMap["eco"],
      },
    ],
  },
  {
    id: 4,
    name: "Lembaga Semi Otonom (LSO)",
    organizations: [
      {
        id: 2,
        name: "U-BIZ",
        desc: "UBiz adalah LSO (Lembaga Semi Otonom) di Universitas Multimedia Nusantara yang berfokus pada pengembangan jiwa kewirausahaan mahasiswa. UBiz menjadi wadah bagi mahasiswa untuk belajar dan mempraktikkan langsung ilmu bisnis, mulai dari perencanaan, pemasaran, hingga penjualan jasa. Melalui kegiatan seperti pelatihan dan proyek bisnis, UBiz bertujuan membekali anggotanya dengan pengalaman nyata agar siap menghadapi dunia bisnis di masa depan.",
        clue: "Organisasi ini ngajarin kamu jualan jasa bareng tim, tapi jangan kaget kalau kamu malah dapet cuan beneran!",
        password: "UBIZ",
      },
      {
        id: 3,
        name: "U-STORE",
        desc: "USTORE adalah koperasi mahasiswa Universitas Multimedia Nusantara (UMN) yang menjadi wadah bagi mahasiswa untuk belajar dan berkembang dalam dunia bisnis, mulai dari riset, desain produk, pengelolaan stok, hingga pemasaran. Terdiri dari dua divisi utama yaitu Marketing dan Product Development. USTORE memasarkan produk seperti jersey, sweater, hoodie, kaos, lanyard, serta e-money dan flazz melalui ANUTARA. Mahasiswa yang aktif berkontribusi juga mendapat upah berupa SHU (Sisa Hasi Usaha). Dengan logo burung hantu sebagai simbol kecerdasan dan semangat belajar, USTORE hadir untuk mengembangkan potensi mahasiswa dalam berwirausaha dan bekerja sama.",
        clue: "Supplier Anutara",
        password: "USTORE",
      },
      {
        id: 4,
        name: "Kompas Corner",
        desc: "Kompas Corner adalah organisasi yang dibuat oleh Kompas Muda dan berada di bawah pengawasan langsung Harian Kompas dan Kemahasiswaan UMN yang didirikan pada tanggal 2 Mei 2013. Kompas Corner memiliki ruangan khusus yang dilengkapi dengan berbagai fasilitas seperti Komputer, Buku-buku terbitan Kompas, Papan tulis, Kursi, Meja, dan Bantal. Ruangan Kompas Corner berfungsi sebagai ruang diskusi, tempat untuk membaca buku, dan tempat untuk mengerjakan tugas.",
        clue: "Menjembatani mahasiswa UMN untuk mempunyai koneksi terhadap informasi Kompas Gramedia.",
        password: "KOMPASCORNER",
      },
      {
        id: 5,
        name: "Duta Anti Narkoba",
        desc: "Duta Anti Narkoba (DAN) UMN merupakan LSO (Lembaga Semi Otonom) yang menyuarakan gerakan anti narkoba baik secara internal maupun eksternal, sesuai dengan esensi kampus yang menolak segala bentuk penyalahgunaan narkoba Tagline “Stay Sharp, Stay Strong, Stay Clean!” Ingin membawakan pesan untuk para mahasiswa agar menjauhi segala bentuk narkoba atau narkotika sehingga bisa menciptakan lingkungan yang sehat dan bebas narkoba.",
        clue: "Organisasi ini mempromosikan pentingnya lingkungan ang sehat dan bebas dari zat adiktif yang membahayakan tubuh manusia.",
        password: "DAN",
      },
      {
        id: 6,
        name: "UMN Medical Center (UMN Medic)",
        desc: "UMN Medical Center merupakan organisasi yang bisa menjadi pertolongan pertama bagi sivitas akademika UMN yang membutuhkan bantuan kesehatan secara cepat dan sigap. Di sini, anggota tidak hanya belajar seputar obat-obatan dan penggunaan alat kesehatan, tetapi juga dilatih untuk tanggap dalam situasi darurat medis. Dengan bergabung sebagai anggota Medic, mahasiswa akan mendapatkan 3 SKKM dan berkesempatan memperoleh berbagai benefit menarik seperti tiket acara gratis maupun merchandise dari pengajuan jasa, sebagai bentuk apresiasi atas kontribusi dalam kegiatan kampus.",
        clue: "Ku gendong tas merah ku (ada tanda plus nya tapi) di pundak!",
        password: "MEDIC",
        fallbackLogo: logoMap["medic"],
      },
    ],
  },
  {
    id: 5,
    name: "Media Kampus",
    organizations: [
      {
        id: 7,
        name: "UMN TV",
        desc: "UMN TV adalah media kampus televisi berbasis streaming yang menjadi wadah berkarya serta pengaplikasian ilmu di bangku perkuliahan. UMN TV diresmikan pada 31 Maret 2015 di bawah naungan fakultas Ilmu Komunikasi. Namun pengurus dan anggota UMN TV berasal dari fakultas yang berbeda-beda. Di sini kamu bisa coba serunya bikin program, jadi host, ngeliput acara, sampai ngulik dunia broadcasting dari depan kamera sampai belakang layar.",
        clue: "Organisasi ini siap bikin kamu jago tampil di depan kamera atau di balik layar sambil seru-seruan di dunia pertelevisian kampus.",
        password: "UMNTV",
      },
      {
        id: 8,
        name: "ULTIMAGZ",
        desc: "Ultimagz merupakan satu-satunya media kampus independen dengan output utama majalah yang berlokasi di Universitas Multimedia Nusantara (UMN) sejak 2007. Ultimagz konsisten berkarya hingga saat ini dengan menerbitkan produk jurnalistik berupa majalah cetak, majalah digital, dan portal daring artikel harian www.ultimagz.com. Ultimagz juga terus berinovasi dengan menciptakan produk-produk berita yang lain, seperti infografik, visual interaktif Fokus (fokus.ultimagz.com), majalah digital interaktif, dan video di kanal YouTube.",
        clue: "Satu-satunya media kampus independen di UMN yang sekalinya bersuara bisa membuat satu UMN bergetar!",
        password: "ULTIMAGZ",
      },
      {
        id: 9,
        name: "UMN RADIO",
        desc: "UMN Radio adalah organisasi media kampus yang berbasis radio komunitas di Universitas Multimedia Nusantara. UMN Radio telah diresmikan dan mengudara sejak 2011 di 107.7FM dengan tagline “Inspiring Change for Tomorrow”. Harapannya, UMN Radio dapat menjadi wadah aspirasi yang menginspirasi sehingga dapat membawa dampak positif kepada masyarakat melalui media radio.",
        clue: "Kami lahir dari gelombang suara, berdetak dalam harmoni, dan selalu mengudara dengan inspirasi untuk esok hari.",
        password: "UMNRADIO",
      },
      {
        id: 10,
        name: "UMN Journalism Center (UMN Juice)",
        desc: "UMN Journalism Center (JUICE) adalah media kampus yang bergerak di bidang visual jurnalistik berupa foto jurnalistik, video dokumenter, video informatif, dan infografis. Kegiatan jurnalistik yang dilakukan UMN Juice antara lain: hunting foto, produksi video dokumenter, produksi video informatif, photostory, infografis setiap minggunya. Selain itu, UMN JUICE mengadakan workshop, lomba tahunan, dan pameran foto yang berkaitan dengan jurnalistik, serta screening dan bedah film dokumenter dengan mendatangkan tim produksi dari film-film dokumenter eksternal.",
        clue: "Kami ga bikin jus..",
        password: "UMNJUICE",
      },
    ],
  },
  {
    id: 6,
    name: "UKM Seni dan Budaya",
    organizations: [
      {
        id: 45,
        name: "QORIE",
        desc: "Qorie merupakan sebuah komunitas untuk mahasiswa/i UMN yang berkeinginan mengeksplorasi bakat dan minat mereka dalam bidang seni dan kebudayaan Korea Selatan. Qorie memiliki empat divisi yaitu Hantalk, Budaya, K-Code, dan K-Voice yang bergerak mewakilkan bidang yang berbeda dari kebudayaan Korea Selatan.",
        clue: "Rumahnya para K-Popers UMN",
        password: "QORIE",
        fallbackLogo: logoMap["qorie"],
      },
      {
        id: 46,
        name: "J-CAFE",
        desc: "J-CAFE (Japanese Culture and Animation Forté) merupakan organisasi di UMN yang menjadi wadah bagi mahasiswa yang tertarik pada budaya Jepang. Kegiatan J-CAFE mencakup berbagai bidang seperti musik anisong, cosplay karakter favorit dari anime atau game, arts and craft, budaya dan kuliner, visual novel, hingga trading card game. Selain aktivitas rutin, J-CAFE juga mengadakan berbagai event seru seperti Malam Keakraban, Main Gathering, dan festival tahunan yang merayakan kecintaan terhadap budaya Jepang.",
        clue: "Biarpun jauh dari Jepang, kebersamaannya tetap di hati",
        password: "JCAFE",
        fallbackLogo: logoMap["jcafe"],
      },
      {
        id: 11,
        name: "MUFOMIC",
        desc: "Multimedia Face of Music (MUFOMIC) adalah Unit Kegiatan Mahasiswa (UKM) di Universitas Multimedia Nusantara yang jadi ruang berkumpulnya para mahasiswa dengan ketertarikan serius di dunia musik, baik sebagai musisi maupun bagian dari tim produksi di belakang panggung. MUFOMIC telah menjadi wadah bagi kamu yang ingin memperdalam pengetahuan, skill, dan pengalaman di ranah live music.",
        clue: "Tempat gitar, drum, dan vokal berpadu jadi satu harmoni.",
        password: "MUFOMIC",
      },
      {
        id: 12,
        name: "OBSCURA",
        desc: "Obscura merupakan Unit Kegiatan Mahasiswa (UKM) yang bergerak di bidang fotografi dibawah naungan Universitas Multimedia Nusantara sejak tahun 2007. Obscura juga tidak hanya diperuntukkan kepada mahasiswa/i yang memiliki kemampuan fotografi sehingga Obscura terbuka bagi kalangan yang ingin belajar terkait fotografi.",
        clue: "Mata ketiga yang membekukan momen dalam cahaya.",
        password: "OBSCURA",
        fallbackLogo: logoMap["obscura"],
      },
      {
        id: 13,
        name: "Teater KATAK",
        desc: "Teater KataK merupakan UKM yang berdirikan pada tahun 2007 dengan nama Autumn, hingga pada tanggal 12 Juni 2009, nama tersebut diganti menjadi Teater KataK. KataK merupakan singkatan dari  'Komunitas Anak Teater Kampus'. Teater KataK kerap menyelenggarakan berbagai produksi pementasan dan menjadi wadah bagi mahasiswa UMN untuk menyalurkan minat serta bakat seni pertunjukan.",
        clue: "Berani Melompat Lebih Tinggi Melewati Batas yang Ada",
        password: "KATAK",
      },
      {
        id: 14,
        name: "ULTIMA TOYS",
        desc: "ULTIMA Toys merupakan Unit Kegiatan Mahasiswa (UKM) yang berdiri sejak tahun 2014. UKM ini berfokus pada kegiatan fotografi dan kustomisasi mainan, yang ditujukan untuk memberikan wadah bagi mahasiswa dalam menyalurkan minat dan kreativitas.",
        clue: "Bukan fotografi biasa, di sini kamu bisa eksplorasi kreativitas dengan berbagai mainan",
        password: "UTOYS",
      },
      {
        id: 15,
        name: "Street Dance UMN",
        desc: "Street Dance UMN merupakan Unit Kegiatan Mahasiswa di Universitas Multimedia Nusantara yang menjadi wadah bagi mahasiswa yang memiliki ketertarikan terhadap street dance. Komunitas ini memberikan ruang untuk berekspresi, berlatih, dan berkolaborasi dalam berbagai gaya tari seperti hip-hop, waacking, popping, hingga locking. Dengan semangat kekeluargaan dan kreativitas yang tinggi, Street Dance UMN aktif tampil dalam berbagai acara kampus maupun kompetisi eksternal.",
        clue: "Tempat untuk saling bertukar energi melalui gerakan bebas (freestyle)",
        password: "STREETDANCE",
      },
      {
        id: 16,
        name: "Ultima Sonora (ULSON)",
        desc: "Ultima Sonora merupakan Paduan Suara Mahasiswa di bawah naungan Universitas Multimedia Nusantara (UMN) yang berdiri pada tahun 2007. Bersama conductor kami, bapak Antonius Ria Deni Sulistya, Ultima Sonora menjadi salah satu Unit Kegiatan Mahasiswa Seni dan Budaya yang populer di kalangan civitas UMN karena aktif berpartisipasi dalam kegiatan paduan suara baik secara regional, nasional, maupun internasional.",
        clue: "Kelompok paduan suara ini pernah menjadi salah satu pengisi lagu dan supporting cast di Youtube Rewind 2023.",
        password: "ULSON",
      },
      {
        id: 17,
        name: "UMN Symphony Orchestra (USO)",
        desc: "UMN Symphony Orchestra adalah UKM seni budaya yang berfokus pada musik orkestra. USO sudah berdiri selama 9 tahun. USO terdiri dari 4 section; strings, woodwind, brass, dan combo. USO menjadi wadah bagi mahasiswa yang memiliki bakat & minat dalam bidang musik terlepas dari tingkat keterampilan yang dimiliki. Semua bisa belajar meningkatkan talenta musik mereka & menyalurkan hobi mereka melalui USO.",
        clue: "Merupakan satu-satunya orkestra yang terdapat di UMN",
        password: "USO",
      },
      {
        id: 18,
        name: "UMN Traditional Dance (TRACCE)",
        desc: "Tracce merupakan sebuah Unit Kegiatan Mahasiswa yang bergerak di bidang seni tari dan musik tradisional Indonesia. Tracce menjadi poin penting UKM UMN dalam melestarikan dan mempromosikan budaya Indonesia di dalam kampus maupun luar kampus. Tracce memiliki 2 divisi, yaitu Reguler (RG) dan Ratoe Jaroe (RJ). Divisi Reguler akan mempelajari berbagai macam tarian dan musik dari Sabang sampai Merauke. Sedangkan Ratoe Jaroe merupakan divisi yang fokus pada tarian dan musik yang berasal daerah Aceh.",
        clue: "UKM ini mengajak kamu menari sekaligus mengekspresikan diri dalam alunan musik khas Indonesia",
        password: "TRACCE",
      },
    ],
  },
  {
    id: 7,
    name: "UKM Sains dan Sosial",
    organizations: [
      {
        id: 19,
        name: "RENCANG",
        desc: "Rencang merupakan sebuah komunitas sosial yang berdiri di bawah naungan Universitas Multimedia Nusantara (UMN) pada tanggal 23 September 2007. Rencang memiliki logo Anjing Siberian Husky untuk menunjukan kesetiaan Rencang kepada masyarakat dan juga menggambarkan kehangatan sebagai keluarga. Melalui berbagai kegiatan sosial, Rencang menjadi wadah untuk belajar, melayani, dan berkontribusi secara nyata, mulai dari aksi sosial langsung, kampanye sosial, hingga edukasi sosial.",
        clue: "Berlogo anjing, tapi bukan komunitas pecinta anjing",
        password: "RENCANG",
      },
      {
        id: 20,
        name: "UMN Robotic Club",
        desc: "Robotic Club UMN merupakan UKM yang berdiri dibawah program studi Teknik elektro sejak 2021 yang di sebut generasi 0 tujuan dari UKM ini di dirikan untuk mengasah skill mahasiswa yang ingin belajar mengenai robotika baik dari program studi Teknik Elekto maupun luar. dengan visi utama memasuki ajang lomba KRI ( Kompetisi Robot Indonesia) yang di selenggarakan oleh Pemerintah. Organisasi ini adalah ruang di mana ide sederhana bisa tumbuh menjadi karya luar biasa. Di sinilah setiap individu, didorong untuk mau belajar untuk mempersiapkan diri di masa depan",
        clue: "UKM ini bikin kamu pintar merakit sekaligus belajar teknik elektro!",
        password: "ROBOTIC",
      },
      {
        id: 21,
        name: "Game Development Club (GDC)",
        desc: "GDC adalah UKM yang bergerak di bidang pengembangan game dan tergabung dalam komunitas mahasiswa Universitas Multimedia Nusantara sejak 2010. Di dalam GDC, mahasiswa dapat mengembangkan keterampilan dalam desain, pemrograman, dan seni game, serta berkesempatan untuk berkolaborasi dalam proyek-proyek kreatif dan mengikuti berbagai kompetisi yang memperkaya pengalaman.",
        clue: "Organisasi ini selalu berpartisipasi dalam pelaksanaan game jam internasional yang bernama Global Game Jam sejak 2016 sampai sekarang.",
        password: "GDC",
      },
      {
        id: 22,
        name: "UMN Programming Club (UMN PC)",
        desc: "UKM yang merupakan sarana bagi mahasiswa yang memiliki minat untuk mengembangkan keterampilan dalam bidang competitive programming serta aktif berpartisipasi dalam berbagai perlombaan competitive programming.",
        clue: "Otak kami senang diajak sparring dalam problem solving dan competitive programming",
        password: "UMNPC",
      },
      {
        id: 23,
        name: "Mahasiswa Pecinta Alam (MAPALA)",
        desc: "MAPALA UMN menjadi wadah bagi mahasiswa yang memiliki ketertarikan pada kegiatan alam bebas seperti pendakian gunung, susur gua, dan panjat tebing. MAPALA memberikan pengalaman yang unik serta meningkatkan keterampilan survival. Selain itu, MAPALA juga berkontribusi aktif dalam upaya pelestarian lingkungan.",
        clue: "Berteduh di bawah bintang, mendaki hingga awan, dan memanjat tebing setinggi harapan kami bukan sekadar berkemah, melainkan merayakan keberanian, canda tawa, dan persaudaraan di pelukan alam.",
        password: "MAPALA",
      },
      {
        id: 47,
        name: "UMN English Student Council (UESC)",
        desc: "UESC adalah satu-satunya organisasi di UMN yang berfokus pada penggunaan Bahasa Inggris. Kami mengembangkan keterampilan berbasis bahasa Inggris melalui 4 divisi, yaitu Speech, Debate, MUN, dan Scrabble. Melalui berbagai kegiatan, kami bertujuan untuk menumbuhkan komunitas berbahasa Inggris di lingkungan UMN.",
        clue: "Komunitas yang membuat bahasa Inggris jadi sahabat sehari-hari.",
        password: "UESC",
        fallbackLogo: logoMap["uesc"],
      },
    ],
  },
  {
    id: 8,
    name: "UKM Olahraga",
    organizations: [
      {
        id: 24,
        name: "SPECTRE",
        desc: "UMN Spectre adalah Unit Kegiatan Mahasiswa yang berfokus pada dunia film action, mulai dari memerankan aksi stunt hingga mempelajari teknik pengambilan gambar yang memukau. Anggotanya dilatih untuk melakukan pertarungan tangan kosong, koreografi senjata, adegan jatuh dramatis, hingga menguasai keterampilan menjadi camera operator yang mampu mengambil momen penuh adrenalin di tengah aksi. Sebagai satu-satunya UKM stunt dan film action di Indonesia, Spectre adalah rumah bagi mereka yang ingin menyatukan seni peran, aksi, dan sinematografi menjadi karya layaknya film layar lebar.",
        clue: "Di sini kita tidak cuma jago jatuh dramatis, tapi juga bisa bikin kamu terlihat keren saat jatuh di depan kamera.",
        password: "SPECTRE",
      },
      {
        id: 25,
        name: "CAPOIERA",
        desc: "Capoeira merupakan budaya dari Brasil yang merupakan seni beladiri dan memiliki unsur Akrobatik, Tarian, dan Musik. Pada tahun 2011 Capoeira di perkenalkan di kampus UMN dan berhasil menjadi Unit Kegiatan Mahasiswa. Dalam Capoeira UMN, mahasiswa dapat mempelajari dan melatih berbagai gerakan Capoeira yang juga bisa membantu melatih kekuatan otot.",
        clue: "Seni bela diri ini menggabungkan gerakan akrobatik dan tarian, dimana kita tidak hanya melatih kekuatan tetapi juga melatih fleksibilitas.",
        password: "CAPOEIRA",
      },
      {
        id: 26,
        name: "LIONS VOLLEYBALL",
        desc: "Lions Volleyball adalah Unit Kegiatan Mahasiswa (UKM) yang menjadi rumah bagi para pecinta voli di UMN. Tak hanya bermain, tapi juga untuk melatih skill, memperkuat solidaritas tim, dan bertanding diberbagai turnamen voli.",
        clue: "UKM Olahraga ini bisa dimainkan di area pasir loh!",
        password: "VOLLEY",
      },
      {
        id: 27,
        name: "TENIS MEJA",
        desc: "UKM Tenis Meja adalah wadah bagi mahasiswa yang memiliki minat dan bakat dalam olahraga tenis meja untuk mengembangkan kemampuannya dan menjadi sarana untuk menyalurkan hobi.",
        clue: "Bola kecil memantul cepat di atas meja kecil",
        password: "TENISMEJA",
      },
      {
        id: 28,
        name: "TAEKWONDO",
        desc: "UMN Taekwondo merupakan Unit Kegiatan Mahasiswa yang menjadi wadah bagi mahasiswa untuk mengembangkan minat, bakat, dan potensi diri dalam seni bela diri Taekwondo. Tidak hanya fokus pada teknik dan fisik, organisasi ini juga menanamkan nilai-nilai disiplin, sportivitas, dan solidaritas antaranggota. Dengan suasana latihan yang menyenangkan namun tetap serius, UMN Taekwondo telah berhasil mencetak berbagai prestasi membanggakan di tingkat universitas, regional, hingga nasional. Di samping itu, kekeluargaan yang erat membuat setiap anggota merasa memiliki tempat untuk tumbuh bersama, baik di dalam maupun di luar matras.",
        clue: "UKM ini mengajarkan bahwa setiap tendangan yang tepat tak hanya melatih fisik, tapi juga membantu melepas stres akibat tugas yang menumpuk.",
        password: "TAEKWONDO",
      },
      {
        id: 29,
        name: "LIONS FUTSAL",
        desc: "Lions Futsal UMN merupakan UKM yang mewadahi minat dan bakat mahasiswa dalam olahraga futsal, baik untuk kategori putra maupun putri. UKM ini berperan aktif dalam mengembangkan keterampilan teknis, strategi permainan, dan sportivitas anggotanya melalui latihan rutin, uji tanding, serta partisipasi dalam berbagai kompetisi internal maupun eksternal. Selain menjadi sarana pengembangan prestasi, Lions Futsal UMN juga menjadi media pembentukan karakter mahasiswa melalui kerja sama tim, disiplin, dan manajemen waktu yang baik.",
        clue: "Satu bola, yang kejer banyak, yang jaga dua.",
        password: "FUTSAL",
      },
      {
        id: 31,
        name: "LIONS BASKETBALL",
        desc: "Lions Basketball merupakan Unit Kegiatan Mahasiswa (UKM) di Universitas Multimedia Nusantara yang mewadahi minat dan bakat mahasiswa di bidang olahraga basket. Lebih dari sekadar permainan, Lions Basketball membangun semangat sportivitas, kerja sama tim, dan disiplin tinggi. Terbuka bagi mahasiswa dari berbagai tingkat kemampuan, Lions rutin mengadakan latihan, sparring, serta mengikuti berbagai kompetisi kampus dan eksternal. Bersama Lions, kamu nggak cuma berkembang di lapangan tapi juga jadi bagian dari keluarga yang solid dan penuh semangat.",
        clue: "Bukan kandang singa, tapi isinya penuh semangat membara. Bukan kebun binatang, tapi tempat para calon bintang lapangan berkumpul dan bertumbuh. Di sini, menerkam poin itu biasa. Apakah Aku?",
        password: "BASKET",
      },
      {
        id: 32,
        name: "LIONS BADMINTON",
        desc: "Lions Badminton merupakan Unit Kegiatan Mahasiswa di UMN yang menjadi rumah bagi para pecinta bulu tangkis, dari yang baru belajar hingga yang sudah jago. Melalui latihan rutin, sparring, dan keikutsertaan dalam turnamen, Lions Badminton mendorong anggotanya untuk terus berkembang secara sportif, kompetitif, dan solid dalam tim.",
        clue: "bolanya selalu terpontang-panting di udara",
        password: "BADMINTON",
      },
      {
        id: 33,
        name: "FORTIUS E-SPORTS",
        desc: "FORTIUS Esports adalah satu-satunya organisasi esports resmi di Universitas Multimedia Nusantara yang menjadi rumah bagi mahasiswa yang ingin menapaki dunia esports dari berbagai sisi. Tak hanya mencetak pemain bertalenta yang tangguh di liga juara, FORTIUS juga membuka ruang bagi talenta kreatif esports yang terlibat seperti manajemen tim, design graphic, public relations, dan masih banyak lainnya. Di sinilah semangat kompetitif bertemu kolaborasi, dan hobi bertumbuh menjadi prestasi.",
        clue: "Tempat di mana talenta muda belajar, berkembang, dan dilahirkan sebagai juara di dunia digital.",
        password: "FORTIUS",
      },
    ],
  },
  {
    id: 9,
    name: "Fakultas / Himpunan",
    organizations: [
      {
        id: 34,
        name: "Ikatan Mahasiswa Ilmu Komunikasi (IM'KOM)",
        desc: "I'M KOM adalah akronim dari Ikatan Mahasiswa Komunikasi yang merupakan himpunan mahasiswa di bawah naungan Fakultas Ilmu Komunikasi Universitas Multimedia Nusantara. I’M KOM menaungi tiga program studi, yaitu Strategic Communication, Digital Journalism, dan Pembelajaran Jarak Jauh Ilmu Komunikasi (PJJIK). I'M KOM juga memiliki empat program kerja unggulan yaitu Perkenalan Fakultas Ilmu Komunikasi (PFIK), FIKOM Night, I'M KOM CUP, dan Communication Festival (COMMFEST).",
        clue: "Satu-satunya himpunan di Fakultas Ilmu Komunikasi.",
        password: "IMKOM",
      },
      {
        id: 54,
        name: "Himpunan Mahasiswa Film (HMFILM)",
        desc: "Himpunan Film atau biasa disebut sebagai HMFilm merupakan organisasi yang dinaungi oleh prodi Film Fakultas Seni dan Desain. Semulanya film merupakan penjurusan prodi DKV, namun pada tahun 2017, Film dapat berdiri sendiri sebagai sebuah Prodi yang bernama Film dan Televisi, dan HMFTV pun terbentuk. Setelah selang 2 tahun pada tahun 2019, HMFillm beralih nama yang semula merupakan HMFTV menjadi HMFilm yang kita kenal sekarang.",
        clue: "Himpunan ini membantu mahasiswanya untuk membuat karya layar lebar yang luar biasa!",
        password: "HMFILM",
        fallbackLogo: logoMap["hmfilm"],
      },
      {
        id: 35,
        name: "Himpunan Mahasiswa Arsitektur (HIMARS)",
        desc: "HIMARS adalah Himpunan Mahasiswa Arsitektur UMN yang berfungsi untuk mewadahi seluruh kegiatan MahArs baik secara akademik maupun non-akademik. HIMARS juga dibentuk untuk menjadi sarana pengembangan bakat dan minat serta menjadi penampung aspirasi bagi MahArs. HIMARS bekerja sama bersama dengan Prodi untuk selalu memberikan yang terbaik bagi MahArs!",
        clue: "Himpunan ini adalah tempat berkumpulnya para 'MahArs'",
        password: "HIMARS",
      },
      {
        id: 36,
        name: "Himpunan Mahasiswa Desain Komunikasi Visual (HMDKV)",
        desc: "HMDKV (Himpunan Mahasiswa DKV UMN) adalah organisasi yang berfungsi sebagai wadah aspirasi mahasiswa DKV UMN. Dengan value #WeHearWeHelp dan #WeAppreciate, HMDKV siap mendengarkan segala kesulitan, kritik, dan saran, dan juga menjadi wadah apresiasi bagi mahasiswa DKV UMN. Fokus kami dalam pengembangan minat dan bakat adalah meningkatkan partisipasi keraktifan mahasiswa dalam perkuliahan",
        clue: "Himpunan ini merupakan organisasi ramah yang direpresentasikan dengan ilustrasi maskot yang menggemaskan",
        password: "HMDKV",
      },
      {
        id: 37,
        name: "Himpunan Mahasiswa Perhotelan (HMP)",
        desc: "Himpunan Mahasiswa Perhotelan (HMP) adalah ruang berkembangnya mahasiswa Program Studi Perhotelan UMN untuk bebas beropini, berekspresi, dan mengeksplorasi dunia hospitality dari berbagai sisi. Melalui berbagai kegiatan seru seperti pelatihan F&B service, event tematik, hingga kolaborasi antarangkatan, HMP menjadi tempat belajar yang hangat sekaligus menyenangkan.",
        clue: "Di Himpunan ini, kita bisa bebas berekspresi… asal tetap senyum 5cm dan servisnya bintang lima.",
        password: "HMP",
      },
      {
        id: 55,
        name: "Himpunan Mahasiswa Manajemen (HIMMA)",
        desc: "HIMMA (Himpunan Mahasiswa Manajemen) adalah organisasi Himpunan yang menaungi mahasiswa Manajemen UMN. HIMMA menjadi wadah inklusif bagi mahasiswa manajemen untuk menuangkan ide kreatif dan inovatif dari berbagai sudut pandang. HIMMA sebagai organisasi yang fokus pada pengembangkan kompetensi Akademik/Non Akademik bagi Mahasiswa/i Manajemen melalui Program yang Inovatif dan berkelanjutan, agar mahasiswa/i manajemen memiliki pengalaman dan wawasan yang luas untuk menghadapi tantangan internal maupun eksternal dengan mengedepankan integritas dan profesionalitas yang tinggi",
        clue: "Himpunan yang membuat kamu belajar untuk mengatur pengeluaran dan pemasukan",
        password: "HIMMA",
        fallbackLogo: logoMap["himma"],
      },
      {
        id: 56,
        name: "Himpunan Mahasiswa Akutansi Universitas Multimedia Nusantara (HIMTARA)",
        desc: "HIMTARA merupakan Himpunan Akuntansi UMN yang telah berdiri atau terbentuk mulai dari 16 November 2010. HIMTARA bertujuan untuk menggali dan mengembangkan potensi mahasiswa akuntansi dalam bidang akademik maupun nonakademik.",
        clue: "Isinya mahasiswa yang pintar menyusun angka-angka untuk masa depan finansial",
        password: "HIMTARA",
        fallbackLogo: logoMap["himtara"],
      },
      {
        id: 57,
        name: "Himpunan Mahasiswa Informatika (HMIF)",
        desc: "HMIF UMN (Himpunan Mahasiswa Informatika Universitas Multimedia Nusantara) adalah organisasi resmi yang mewakili mahasiswa Teknik Informatika UMN. HMIF UMN berkomitmen mendukung pengembangan diri mahasiswa melalui program kerja, keterampilan, dan kepemimpinan. Kami mendorong kolaborasi, baik secara internal maupun external kampus, serta menyediakan ruang untuk belajar, berkarya, dan berkontribusi bersama.",
        clue: "Himpunan ini jadi titik temu antara logika, kreativitas, dan obrolan random di tengah ngoding—tempat di mana bug menjadi tantangan, teman menjadi solusi, dan pengembangan diri tetap dibalut suasana yang seru dan penuh tawa.",
        password: "HMIF",
        fallbackLogo: logoMap["hmif"],
      },
      {
        id: 38,
        name: "Himpunan Mahasiswa Sistem Informasi (HIMSI)",
        desc: "HIMSI (Himpunan Mahasiswa Sistem Informasi) adalah organisasi mahasiswa untuk prodi Sistem Informasi yang berfungsi mewadahi aspirasi, mengembangkan keilmuan, dan memperkuat network. Semua dilakukan melalui berbagai kegiatan seperti lomba, aksi sosial, dan lainnya.",
        clue: "Jembatan antara teknologi dan solusi informasi.",
        password: "HIMSI",
      },
      {
        id: 39,
        name: "Association of Computer Engineering Student (ACES)",
        desc: "Himpunan mahasiswa dari prodi Teknik Komputer. ACES berperan sebagai sarana koordinasi, komunikasi, dan kolaborasi antar mahasiswa Teknik Komputer untuk menciptakan lingkungan yang aktif, kreatif, dan produktif baik dalam lingkup akademik maupun non-akademik.",
        clue: "Himpunan ini bukan sekadar organisasi, tapi rumah di mana setiap mahasiswa Teknik Komputer saling bertumbuh, berjalan bersama, dan membentuk keluarga baru.",
        password: "ACES",
      },
      {
        id: 58,
        name: "Himpunan Mahasiswa Teknik Elektro dan Fisika (HIMFERA)",
        desc: "HIMFERA (Himpunan Mahasiswa Teknik Fisika dan Elektro) berdiri sejak 2016 sebagai wadah bagi mahasiswa Teknik Fisika dan Elektro UMN untuk belajar, berkreasi, dan membangun kebersamaan. Mulai dari kegiatan akademik, pelatihan, lomba, hingga acara santai, HIMFERA selalu hadir untuk mendukung anggotanya berkembang.",
        clue: "Himpunan ini bisa mengubah tegangan tinggi menjadi semangat tinggi. ⚡",
        password: "HIMFERA",
        fallbackLogo: logoMap["himfera"],
      },
    ],
  },
  {
    id: 10,
    name: "Lembaga Kampus",
    organizations: [
      {
        id: 40,
        name: "NUSAKARA",
        desc: "Nusakara Art & Design Center adalah pusat kreatif dan galeri universitas terkemuka untuk desain, film, dan seni, yang berfungsi sebagai platform kolaboratif dinamis untuk mendorong inovasi, pembelajaran interdisipliner, dan pertumbuhan kreatif.",
        clue: "“Bangunan tanpa pintu ajaib, tetapi bisa kalian masuki dengan membawa karya.”",
        password: "NUSAKARA",
      },
      {
        id: 59,
        name: "UMN Library",
        desc: "UMN Library bukan sekadar tempat meminjam buku, tapi juga pusat komunitas literasi yang mendorong mahasiswa untuk berpikir kritis, berbagi ide, dan tumbuh bersama lewat berbagai program seperti Booktopia dan GERILYA. Di sinilah tempat mahasiswa menemukan ruang yang tenang untuk belajar, komunitas yang suportif, dan pengalaman literasi yang menyenangkan.",
        clue: "Bukan orang nerd, cuman orang yang suka menciptakan dunia baru dari halaman dan percakapan",
        password: "LIBRARY",
        fallbackLogo: logoMap["library"],
      },
      {
        id: 60,
        name: "Campus Visit",
        desc: "Campus Visit atau yang sering dikenal dengan CamVis merupakan organisasi independen UMN yang fokusnya pada kegiatan kunjungan kampus bagi pelajar SMA/SMK serta masyarakat umum untuk lebih mengenal lingkungan akademik dan fasilitas dari Universitas Multimedia Nusantara. Tujuan kami adalah untuk memberikan pengalaman dan gambaran yang tak terlupakan mengenai UMN kepada calon mahasiswa baru!",
        clue: "Satu-satunya organisasi yang langsung disupervisi oleh marketing dan satu-satunya organisasi yang bisa membuatmu memenuhi target 10K langkah setiap hari xixi!",
        password: "CAMVIS",
        fallbackLogo: logoMap["camvis"],
      },
      {
        id: 41,
        name: "Skystar Ventures",
        desc: "Skystar Ventures adalah unit bisnis UMN yang dirancang untuk mewujudkan jiwa kewirausahaan mahasiswa melalui program inkubasi bisnis selama 6 bulan dan program lainnya seperti kompetisi atau workshop. Skystar Ventures dikelola oleh tim profesional dan bekerja sama dengan pihak-pihak berpengalaman dalam pengelolaan bisnis.",
        clue: "Melalui kegiatan ini, kamu akan mendapatkan materi pembelajaran, mentor profesional, hingga ruang kantor secara gratis.",
        password: "SKYSTAR",
      },
      {
        id: 42,
        name: "UMN Documentation (UMN DOC)",
        desc: "UMN Documentation (UMN DOC) adalah organisasi multimedia dan broadcasting di bawah naungan Lab Broadcast UMN yang berperan penting dalam dokumentasi dan siaran langsung berbagai acara kampus. Dengan rekam jejak di acara besar seperti Wisuda UMN, Sidang Terbuka Senat / Kuliah Perdana, PEKANTARA, simulasi kebencanaan, konser-konser sampai beberapa seminar dan talkshow, UMN DOC menjadi saksi visual dari setiap momen penting di UMN.",
        clue: "Kami selalu hadir di balik layar... tapi hasil kerja kami ada di mana-mana 📸",
        password: "UMNDOC",
      },
    ],
  },
  {
    id: 11,
    name: "Komunitas",
    organizations: [
      {
        id: 61,
        name: "UMN Gate",
        desc: "UMN Gate merupakan wadah bagi mahasiswa Universitas Multimedia Nusantara yang bergerak dalam bidang distribusi dan pengarsipan. Wadah bagi mahasiswa film UMN untuk dapat belajar proses pengarsipan dan distribusi film festival.",
        clue: "Komunitas ini bisa bikin film layar lebar jadi tersebar luas",
        password: "UMNGATE",
        fallbackLogo: logoMap["umngate"],
      },
      {
        id: 43,
        name: "POPSICLE",
        desc: "Popsicle atau Popcorn Cinema Club merupakan sebuah komunitas untuk mahasiswa/mahasiswi pecinta film Universitas Multimedia. Dimana, Popsicle aktif dalam mengadakan screening rutin film-film pendek dari berbagai sumber dan menghadirkan pembicara untuk seminar dan screening. Popsicle juga aktif dalam penyebaran informasi seputar agenda maupun pemutaran film melalui media sosial.",
        clue: "Komunitas yang hadir untuk setiap kalangan pecinta film yang ada di UMN",
        password: "POPSICLE",
      },
      {
        id: 44,
        name: "Kelompok Studi Pasar Modal (KSPM) UMN",
        desc: "Kelompok Studi Pasar Modal UMN merupakan organisasi sekaligus tempat belajar tidak hanya bagi mahasiswa UMN namun juga untuk publik. KSPM UMN berada dibawah naungan Bursa Efek Indonesia dan berkolaborasi dengan Philip Sekuritas. Hal tersebut membuat KSPM UMN berhasil growth dan 'langganan' menang Highest Volume Transaction, sampai 80 Miliar Rupiah. Kami juga pastinya siap membantu kalian untuk belajar, berkembang dan juga mempraktekan ilmu investasi kalian baik sebagai individual investor atau sebagai persiapan menuju karir profesional kalian! (sssttt... udah banyak alumni KSPM yang merasakan berdinamika di dunia high finance lohh)",
        clue: "Kita mau kalian terus bertumbuh, berkembang, dan pastinya cuan! Baik dari Portofolio Investasi sampai Softskill dan Pengalaman kalian.",
        password: "KSPM",
      },
      {
        id: 30,
        name: "ULTIMA AIKIDO",
        desc: "Ultima Aikido adalah komunitas kampus yang mempelajari seni bela diri asal Jepang, yaitu Aikido. Teknik Aikido bukanlah teknik mematikan, melainkan teknik untuk melumpuhkan lawan secara efektif tanpa mencederainya. Berbeda dengan bela diri lain, Aikido tidak dipertandingkan. Selain melatih fisik dan keterampilan bela diri, anggota juga diajarkan tatakrama, budi pekerti, serta sopan santun yang dapat diterapkan dalam kehidupan sehari-hari.",
        clue: "Kami tidak bertarung untuk menang, melainkan bergerak untuk memahami. Karena setiap gerakan adalah dialog, bukan pertempuran.",
        password: "AIKIDO",
      },
    ],
  },
];
